name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Linting...
      run: |
        isort --check --diff tradestation/ tests/
        flake8 --count --show-source --statistics tradestation/ tests/
        mypy -p tradestation
    - name: Testing...
      run: |
        python -m pytest --cov=tradestation --cov-report=term-missing tests/ --cov-fail-under=95
      env:
        TS_API_KEY: ${{ secrets.TS_API_KEY }}
